import Link from "next/link";

export const metadata = {
    title : 'MIT-Register',
    description : 'Generated by Next.js'
}

const navlinks = [
    {name: 'Register', href: '/register'},
    {name: 'Login', href: '/login'},
    {name: 'ForgotPassword', href: '/forgotpwd'}
]

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body>
            {children}
            {
                navlinks.map((link)=>{
                    return(
                        <Link href={link.href}
                        key={link.name}
                        className="">
                            {link.name}
                        </Link>
                    )
                })
            }
        </body>
      </html>
    );
  }
  